import { AuthUserProvider } from "./context/AuthUserContext"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <AuthUserProvider>
        <body>{children}</body>
        </AuthUserProvider>
    </html>
  )
}